// <auto-generated />
using AggroCom.Brokers.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggroCom.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20241220142815_CreateAllTablesAddProductTwo")]
    partial class CreateAllTablesAddProductTwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.ProductOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionRu")
                        .HasColumnType("longtext");

                    b.Property<string>("AdditionUz")
                        .HasColumnType("longtext");

                    b.Property<string>("DesRu")
                        .HasColumnType("longtext");

                    b.Property<string>("DesUz")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("KimyoviySinfiRu")
                        .HasColumnType("longtext");

                    b.Property<string>("KimyoviySinfiUz")
                        .HasColumnType("longtext");

                    b.Property<string>("PreparatShakliRu")
                        .HasColumnType("longtext");

                    b.Property<string>("PreparatShakliUz")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductPicture")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("QadogiRu")
                        .HasColumnType("longtext");

                    b.Property<string>("QadogiUz")
                        .HasColumnType("longtext");

                    b.Property<string>("TasirModdaRu")
                        .HasColumnType("longtext");

                    b.Property<string>("TasirModdaUz")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleRu")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleUz")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProductOnes");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.TableOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BegonaQarshiRu")
                        .HasColumnType("longtext");

                    b.Property<string>("BegonaQarshiUz")
                        .HasColumnType("longtext");

                    b.Property<string>("CheklovlarRu")
                        .HasColumnType("longtext");

                    b.Property<string>("CheklovlarUz")
                        .HasColumnType("longtext");

                    b.Property<string>("EkinTuriRu")
                        .HasColumnType("longtext");

                    b.Property<string>("EkinTuriUz")
                        .HasColumnType("longtext");

                    b.Property<int>("MavsumNechta")
                        .HasColumnType("int");

                    b.Property<int>("ProductOneId")
                        .HasColumnType("int");

                    b.Property<string>("SarfMeyoriRu")
                        .HasColumnType("longtext");

                    b.Property<string>("SarfMeyoriUz")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductOneId");

                    b.ToTable("TableOnes");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.TableOne", b =>
                {
                    b.HasOne("AggroCom.Models.Foundations.ProductOnes.ProductOne", null)
                        .WithMany("TableOnes")
                        .HasForeignKey("ProductOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.ProductOne", b =>
                {
                    b.Navigation("TableOnes");
                });
#pragma warning restore 612, 618
        }
    }
}
