// <auto-generated />
using System;
using AggroCom.Brokers.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggroCom.Migrations
{
    [DbContext(typeof(StorageBroker))]
    partial class StorageBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AggroCom.Models.Foundations.Contacts.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.Katalogs.Katalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePicture")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Katalogs");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.News.New", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescribtionRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescribtionUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewPicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleUz")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.Photos.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.ProductOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("KimyoviySinfiRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("KimyoviySinfiUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparatShakliRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparatShakliUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductPicture")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QadogiRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("QadogiUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("TasirModdaRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TasirModdaUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleUz")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductOnes");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.TableOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BegonaQarshiRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("BegonaQarshiUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirgaSarfRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirgaSarfUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("EkinTuriRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("EkinTuriUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Onlsum")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductOneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SarfMeyoriRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("SarfMeyoriUz")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductOneId");

                    b.ToTable("TableOnes");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductTwos.ProductTwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DesRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionUZ")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductIcon")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductPicture")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductTwoType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SarfRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("SarfUz")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleUz")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductTwos");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductTwos.TableTwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foiz")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameUz")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductTwoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductTwoId");

                    b.ToTable("TableTwos");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.TableOne", b =>
                {
                    b.HasOne("AggroCom.Models.Foundations.ProductOnes.ProductOne", null)
                        .WithMany("TableOnes")
                        .HasForeignKey("ProductOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductTwos.TableTwo", b =>
                {
                    b.HasOne("AggroCom.Models.Foundations.ProductTwos.ProductTwo", null)
                        .WithMany("TableTwos")
                        .HasForeignKey("ProductTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductOnes.ProductOne", b =>
                {
                    b.Navigation("TableOnes");
                });

            modelBuilder.Entity("AggroCom.Models.Foundations.ProductTwos.ProductTwo", b =>
                {
                    b.Navigation("TableTwos");
                });
#pragma warning restore 612, 618
        }
    }
}
